name: Validate Code

on: pull_request

jobs:
  validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [11.15]

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}

      - run: npm install
      - run: npm run lint
      - run: npm run test
